module_enable_status:
  dpc: False
  blc: False
  aaf: False
  awb: False
  cnf: False
  cfa: True
  ccm: False
  gac: True
  csc: False
  nlm: False
  bnf: False
  eeh: False
  fcs: False
  hsc: False
  bcc: False

hardware:
  raw_width: 6080
  raw_height: 4044
  raw_bit_depth: 14
  bayer_pattern: rggb


# -------------------- Module Algorithms Parameters --------------------

dpc:
  diff_thres: 30

blc:
  bl_r: 0                             # a subtractive value, not additive!
  bl_gr: 0
  bl_gb: 0
  bl_b: 0
  alpha: 0                            # x1024
  beta: 0                             # x1024

aaf: ~

awb:
  r_gain: &r_gain 1860                # x1024
  gr_gain: 1024                       # x1024
  gb_gain: 1024                       # x1024
  b_gain: &b_gain 1280                # x1024

cnf:
  thres: 0
  r_gain: *r_gain                     # x1024
  b_gain: *b_gain                     # x1024

cfa: ~

ccm:
  ccm:
    - [ 1670, -508, -139, 0 ]          # x1024, copied from dcraw.c
    - [ -20, 1404, -360, 0 ]
    - [ 58, -406, 1372, 0 ]

gac:
  gain: 256                           # x256
  gamma: 0.5

csc:
  csc:
    - [ 263, 516, 100, 16384 ]        # x1024
    - [ -152, -298, 450, 131072 ]
    - [ 450, -377, -73, 131072 ]

nlm:
  search_window_size: 9
  patch_size: 3
  h: 15

bnf:
  rw: [ 0, 8, 16, 32 ]
  diff_thres: [ 128, 32, 8 ]
  dw:
    - [ 8, 12, 32, 12, 8 ]
    - [ 12, 64, 128, 64, 12 ]
    - [ 32, 128, 1024, 128, 32 ]
    - [ 12, 64, 128, 64, 12 ]
    - [ 8, 12, 32, 12, 8 ]

eeh:
  flat_thres: 0                       # delta <= flat_thres: set delta to 0
  middle_thres: 4                     # flat_thres < delta <= middle_thres: reduce delta
  edge_thres: 16                      # middle_thres < delta <= edge_thres: keep delta unchanged
                                      # edge_thres < delta: increase delta
  edge_gain: 1024                     # x256
  delta_thres: 64

fcs:
  delta_min: 8
  delta_max: 16
  flat_gain: 256                      # x256
  edge_gain: 0                        # x256

hsc:
  hue_degree: 0                       # in degree
  saturation_gain: 256                # x256

bcc:
  brightness_offset: 0
  contrast_gain: 256                  # x256
