module_enable_status:
  dpc: True
  blc: True
  aaf: True
  awb: True
  cnf: True
  cfa: True
  ccm: True
  gac: True
  csc: True
  nlm: True
  bnf: True
  eeh: True
  fcs: True
  hsc: True
  bcc: True
  scl: False

hardware:
  raw_width: 1920
  raw_height: 1080
  raw_bit_depth: 10
  bayer_pattern: rggb


# -------------------- Module Algorithms Parameters --------------------

dpc:
  diff_threshold: 30

blc:
  bl_r: 0                             # a subtractive value, not additive!
  bl_gr: 0
  bl_gb: 0
  bl_b: 0
  alpha: 0                            # x1024
  beta: 0                             # x1024

aaf: ~

awb:
  r_gain: &r_gain 1860                # x1024
  gr_gain: 1024                       # x1024
  gb_gain: 1024                       # x1024
  b_gain: &b_gain 1280                # x1024

cnf:
  diff_threshold: 0
  r_gain: *r_gain                     # x1024
  b_gain: *b_gain                     # x1024

cfa:
  mode: malvar

ccm:
  ccm:
    - [ 1024, 0, 0, 0 ]
    - [ 0, 1024, 0, 0 ]
    - [ 0, 0, 1024, 0 ]

gac:
  gain: 256                           # x256
  gamma: 0.42

csc: ~

nlm:
  search_window_size: 9
  patch_size: 3
  h: 10                               # larger value has stronger smoothing effect

bnf:
  intensity_sigma: 0.8                # larger value has stronger smoothing effect
  spatial_sigma: 0.8                  # larger value has stronger smoothing effect

eeh:
  flat_threshold: 1                   # delta <= flat_threshold: set delta to 0
  middle_threshold: 4                 # flat_threshold < delta <= middle_threshold: reduce delta
  edge_threshold: 8                   # middle_threshold < delta <= edge_threshold: keep delta unchanged
                                      # edge_threshold < delta: increase delta
  edge_gain: 768                      # x256
  delta_threshold: 64

fcs:
  delta_min: 8
  delta_max: 16
  flat_gain: 256                      # x256
  edge_gain: 0                        # x256

hsc:
  hue_offset: 0                       # in degree
  saturation_gain: 256                # x256

bcc:
  brightness_offset: 0
  contrast_gain: 256                  # x256

scl:
  width: 1920
  height: 1080
